name: Compilar AOSP 7

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Preparar entorno y herramientas
        run: |
          sudo apt update
          sudo apt install -y openjdk-8-jdk build-essential curl git python-is-python3 \
            repo libssl-dev zlib1g-dev libncurses5-dev libncursesw5-dev \
            libreadline-dev libsqlite3-dev libgdbm-dev libdb5.3-dev libbz2-dev \
            libexpat1-dev liblzma-dev tk-dev

      - name: Inicializar árbol AOSP 7
        run: |
          mkdir aosp7 && cd aosp7
          git config --global user.name "TuNombre"
          git config --global user.email "tu@email.com"
          repo init -u https://github.com/Jesusdio2/manifest_aosp7.git -b master
          repo sync -j$(nproc)

      - name: Configurar entorno AOSP
        working-directory: aosp7
        run: |
          source build/envsetup.sh
          lunch aosp_arm-eng

      - name: Compilar AOSP
        working-directory: aosp7
        run: |
          make -j$(nproc)
